name: Prettier Check

on:
  push:
    branches:
      - chore/prettier-ci

  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar formatacao com Prettier
        run: npm run format:check
